version: '3.7'

networks:
  rails:

services:
  webpacker:
    image: colinxfleming/dcaf_case_management:latest
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    networks:
      - rails
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: ["./scripts/start_rails.sh"]
    image: colinxfleming/dcaf_case_management:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      mongohost: db
    env_file:
      - .docker/web-variables.env
    depends_on:
      - db
      - webpacker
      - chrome
    networks:
      - rails
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - rails
  # System test-related
  selenium:
    image: selenium/hub
    container_name: rails-selenium
    ports:
      - 4444:4444
    networks:
      - rails
    environment:
      GRID_MAX_SESSION: 10
  chrome:
    image: selenium/node-chrome
    networks:
      - rails
    depends_on:
      - selenium
    environment:
      HUB_HOST: rails-selenium
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
